version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  run_unit_tests:
    jobs:
      - node/test:
          version: "16.10"
          pkg-manager: npm
    store_test_results:
      path: test-results
