VERTEX_SIZE = 50
EDGES_CURVED = True
MARGIN = 64

SENSOR_COLOR = "lightblue"
NEURON_COLOR = "grey"
ACTION_COLOR = "red"

SENSOR_NAMES = ["XPos", "YPos", "Age"]
ACTION_NAMES = ["MoveX", "MoveY"]

PLOT_OUTPUT_EXTENSION = ".png"
